version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: go_mall_postgres
    restart: always
    environment:
      POSTGRES_DB: go_mall
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: go_mall_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"

  redis:
    image: redis:7
    container_name: go_mall_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: go_mall_redis_insight
    restart: always
    ports:
      - "5540:5540"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: go_mall_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # mgmt UI
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: devpass

volumes:
  postgres_data:
  redis_data:
